[package]
name = "text-core"
version = "0.1.0"
edition = "2021"

[dependencies]
text-plugin-api = { path = "../text-plugin-api" }
libloading = "0.8"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
walkdir = "2.4" 