[package]
name = "task-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
task-common = { path = "../task-common" }
tokio = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true } 