[package]
name = "advanced_collections"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A demonstration of advanced collection types in Rust"

[dependencies]
rand = "0.8"
